// Human-readable label <-> numeric code tables for the categorical fields
// in the UCI "Predict students' dropout and academic success" dataset —
// the exact dataset the Day 19/46 model (ml/dropout_model.pkl) was trained
// on. Codes here match the dataset's official variable documentation
// (https://archive.ics.uci.edu/dataset/697) so a selection here still sends
// the model the same numeric code it was trained on; only the UI changes
// from "type a code" to "search/pick a label".

export const MARITAL_STATUS = [
  { code: 1, label: 'Single' },
  { code: 2, label: 'Married' },
  { code: 3, label: 'Widower' },
  { code: 4, label: 'Divorced' },
  { code: 5, label: 'Facto union' },
  { code: 6, label: 'Legally separated' },
];

export const APPLICATION_MODE = [
  { code: 1, label: '1st phase — general contingent' },
  { code: 2, label: 'Ordinance No. 612/93' },
  { code: 5, label: '1st phase — special contingent (Azores Island)' },
  { code: 7, label: 'Holders of other higher courses' },
  { code: 10, label: 'Ordinance No. 854-B/99' },
  { code: 15, label: 'International student (bachelor)' },
  { code: 16, label: '1st phase — special contingent (Madeira Island)' },
  { code: 17, label: '2nd phase — general contingent' },
  { code: 18, label: '3rd phase — general contingent' },
  { code: 26, label: 'Ordinance No. 533-A/99, item b2 (different plan)' },
  { code: 27, label: 'Ordinance No. 533-A/99, item b3 (other institution)' },
  { code: 39, label: 'Over 23 years old' },
  { code: 42, label: 'Transfer' },
  { code: 43, label: 'Change of course' },
  { code: 44, label: 'Technological specialization diploma holders' },
  { code: 51, label: 'Change of institution/course' },
  { code: 53, label: 'Short cycle diploma holders' },
  { code: 57, label: 'Change of institution/course (International)' },
];

// Same codes seed_students.py uses for COURSE_NAMES — kept in sync so a
// seeded student's course and a Risk Predictor selection mean the same code.
export const COURSE = [
  { code: 33, label: 'Biofuel Production Technologies' },
  { code: 171, label: 'Animation and Multimedia Design' },
  { code: 8014, label: 'Social Service (evening attendance)' },
  { code: 9003, label: 'Agronomy' },
  { code: 9070, label: 'Communication Design' },
  { code: 9085, label: 'Veterinary Nursing' },
  { code: 9119, label: 'Informatics Engineering' },
  { code: 9130, label: 'Equinculture' },
  { code: 9147, label: 'Management' },
  { code: 9238, label: 'Social Service' },
  { code: 9254, label: 'Tourism' },
  { code: 9500, label: 'Nursing' },
  { code: 9556, label: 'Oral Hygiene' },
  { code: 9670, label: 'Advertising and Marketing Management' },
  { code: 9773, label: 'Journalism and Communication' },
  { code: 9853, label: 'Basic Education' },
  { code: 9991, label: 'Management (evening attendance)' },
];

export const PREVIOUS_QUALIFICATION = [
  { code: 1, label: 'Secondary education' },
  { code: 2, label: "Higher education — bachelor's degree" },
  { code: 3, label: 'Higher education — degree' },
  { code: 4, label: "Higher education — master's" },
  { code: 5, label: 'Higher education — doctorate' },
  { code: 6, label: 'Frequency of higher education' },
  { code: 9, label: '12th year of schooling — not completed' },
  { code: 10, label: '11th year of schooling — not completed' },
  { code: 12, label: 'Other — 11th year of schooling' },
  { code: 14, label: '10th year of schooling' },
  { code: 15, label: '10th year of schooling — not completed' },
  { code: 19, label: 'Basic education 3rd cycle (9th/10th/11th year) or equivalent' },
  { code: 38, label: 'Basic education 2nd cycle (6th/7th/8th year) or equivalent' },
  { code: 39, label: 'Technological specialization course' },
  { code: 40, label: 'Higher education — degree (1st cycle)' },
  { code: 42, label: 'Professional higher technical course' },
  { code: 43, label: "Higher education — master's (2nd cycle)" },
];

export const NATIONALITY = [
  { code: 1, label: 'Portuguese' },
  { code: 2, label: 'German' },
  { code: 6, label: 'Spanish' },
  { code: 11, label: 'Italian' },
  { code: 13, label: 'Dutch' },
  { code: 14, label: 'English' },
  { code: 17, label: 'Lithuanian' },
  { code: 21, label: 'Angolan' },
  { code: 22, label: 'Cape Verdean' },
  { code: 24, label: 'Guinean' },
  { code: 25, label: 'Mozambican' },
  { code: 26, label: 'Santomean' },
  { code: 32, label: 'Turkish' },
  { code: 41, label: 'Brazilian' },
  { code: 62, label: 'Romanian' },
  { code: 100, label: 'Moldovan' },
  { code: 101, label: 'Mexican' },
  { code: 103, label: 'Ukrainian' },
  { code: 105, label: 'Russian' },
  { code: 108, label: 'Cuban' },
  { code: 109, label: 'Colombian' },
];

// Shared by Mother's and Father's qualification (Father's has 2 extra codes
// — 13 and 20 — that Mother's list doesn't; both lists included as given by
// the dataset documentation).
export const MOTHERS_QUALIFICATION = [
  { code: 1, label: 'Secondary education — 12th year or equivalent' },
  { code: 2, label: "Higher education — bachelor's degree" },
  { code: 3, label: 'Higher education — degree' },
  { code: 4, label: "Higher education — master's" },
  { code: 5, label: 'Higher education — doctorate' },
  { code: 6, label: 'Frequency of higher education' },
  { code: 9, label: '12th year of schooling — not completed' },
  { code: 10, label: '11th year of schooling — not completed' },
  { code: 11, label: '7th year (old)' },
  { code: 12, label: 'Other — 11th year of schooling' },
  { code: 14, label: '10th year of schooling' },
  { code: 18, label: 'General commerce course' },
  { code: 19, label: 'Basic education 3rd cycle (9th/10th/11th year) or equivalent' },
  { code: 22, label: 'Technical-professional course' },
  { code: 26, label: '7th year of schooling' },
  { code: 27, label: '2nd cycle of the general high school course' },
  { code: 29, label: '9th year of schooling — not completed' },
  { code: 30, label: '8th year of schooling' },
  { code: 34, label: 'Unknown' },
  { code: 35, label: "Can't read or write" },
  { code: 36, label: 'Can read without a 4th year of schooling' },
  { code: 37, label: 'Basic education 1st cycle (4th/5th year) or equivalent' },
  { code: 38, label: 'Basic education 2nd cycle (6th/7th/8th year) or equivalent' },
  { code: 39, label: 'Technological specialization course' },
  { code: 40, label: 'Higher education — degree (1st cycle)' },
  { code: 41, label: 'Specialized higher studies course' },
  { code: 42, label: 'Professional higher technical course' },
  { code: 43, label: "Higher education — master's (2nd cycle)" },
  { code: 44, label: 'Higher education — doctorate (3rd cycle)' },
];

export const FATHERS_QUALIFICATION = [
  ...MOTHERS_QUALIFICATION.filter((o) => o.code !== 44),
  { code: 13, label: '2nd year complementary high school course' },
  { code: 20, label: 'Complementary high school course' },
  { code: 25, label: 'Complementary high school course — not concluded' },
  { code: 31, label: 'General course of administration and commerce' },
  { code: 33, label: 'Supplementary accounting and administration' },
  { code: 44, label: 'Higher education — doctorate (3rd cycle)' },
].sort((a, b) => a.code - b.code);

export const MOTHERS_OCCUPATION = [
  { code: 0, label: 'Student' },
  { code: 1, label: 'Legislative/executive directors and managers' },
  { code: 2, label: 'Specialists in intellectual and scientific activities' },
  { code: 3, label: 'Intermediate level technicians and professions' },
  { code: 4, label: 'Administrative staff' },
  { code: 5, label: 'Personal services, security and safety workers, sellers' },
  { code: 6, label: 'Farmers and skilled agriculture/fisheries/forestry workers' },
  { code: 7, label: 'Skilled industry, construction and craft workers' },
  { code: 8, label: 'Installation and machine operators, assembly workers' },
  { code: 9, label: 'Unskilled workers' },
  { code: 10, label: 'Armed forces professions' },
  { code: 90, label: 'Other situation' },
  { code: 99, label: '(blank)' },
  { code: 122, label: 'Health professionals' },
  { code: 123, label: 'Teachers' },
  { code: 125, label: 'ICT specialists' },
  { code: 131, label: 'Intermediate level science and engineering technicians' },
  { code: 132, label: 'Intermediate level health technicians and professionals' },
  { code: 134, label: 'Intermediate level legal/social/sports/cultural technicians' },
  { code: 141, label: 'Office workers, secretaries, data processing operators' },
  { code: 143, label: 'Data, accounting, statistical, financial, registry operators' },
  { code: 144, label: 'Other administrative support staff' },
  { code: 151, label: 'Personal service workers' },
  { code: 152, label: 'Sellers' },
  { code: 153, label: 'Personal care workers and the like' },
  { code: 171, label: 'Skilled construction workers (except electricians)' },
  { code: 173, label: 'Skilled printing/precision/jewellery/artisan workers' },
  { code: 175, label: 'Food processing, woodworking, clothing and craft workers' },
  { code: 191, label: 'Cleaning workers' },
  { code: 192, label: 'Unskilled agriculture/animal production/fisheries workers' },
  { code: 193, label: 'Unskilled extractive industry/construction/transport workers' },
  { code: 194, label: 'Meal preparation assistants' },
];

export const FATHERS_OCCUPATION = [
  { code: 0, label: 'Student' },
  { code: 1, label: 'Legislative/executive directors and managers' },
  { code: 2, label: 'Specialists in intellectual and scientific activities' },
  { code: 3, label: 'Intermediate level technicians and professions' },
  { code: 4, label: 'Administrative staff' },
  { code: 5, label: 'Personal services, security and safety workers, sellers' },
  { code: 6, label: 'Farmers and skilled agriculture/fisheries/forestry workers' },
  { code: 7, label: 'Skilled industry, construction and craft workers' },
  { code: 8, label: 'Installation and machine operators, assembly workers' },
  { code: 9, label: 'Unskilled workers' },
  { code: 10, label: 'Armed forces professions' },
  { code: 90, label: 'Other situation' },
  { code: 99, label: '(blank)' },
  { code: 101, label: 'Armed forces officers' },
  { code: 102, label: 'Armed forces sergeants' },
  { code: 103, label: 'Other armed forces personnel' },
  { code: 112, label: 'Directors of administrative and commercial services' },
  { code: 114, label: 'Hotel, catering, trade and other services directors' },
  { code: 121, label: 'Physical science, maths and engineering specialists' },
  { code: 122, label: 'Health professionals' },
  { code: 123, label: 'Teachers' },
  { code: 124, label: 'Finance, accounting and admin organization specialists' },
  { code: 131, label: 'Intermediate level science and engineering technicians' },
  { code: 132, label: 'Intermediate level health technicians and professionals' },
  { code: 134, label: 'Intermediate level legal/social/sports/cultural technicians' },
  { code: 135, label: 'ICT technicians' },
  { code: 141, label: 'Office workers, secretaries, data processing operators' },
  { code: 143, label: 'Data, accounting, statistical, financial, registry operators' },
  { code: 144, label: 'Other administrative support staff' },
  { code: 151, label: 'Personal service workers' },
  { code: 152, label: 'Sellers' },
  { code: 153, label: 'Personal care workers and the like' },
  { code: 154, label: 'Protection and security services personnel' },
  { code: 161, label: 'Market-oriented farmers and skilled animal production workers' },
  { code: 163, label: 'Subsistence farmers, fishermen, hunters and gatherers' },
  { code: 171, label: 'Skilled construction workers (except electricians)' },
  { code: 172, label: 'Skilled metallurgy and metalworking workers' },
  { code: 174, label: 'Skilled electricity and electronics workers' },
  { code: 175, label: 'Food processing, woodworking, clothing and craft workers' },
  { code: 181, label: 'Fixed plant and machine operators' },
  { code: 182, label: 'Assembly workers' },
  { code: 183, label: 'Vehicle drivers and mobile equipment operators' },
  { code: 192, label: 'Unskilled agriculture/animal production/fisheries workers' },
  { code: 193, label: 'Unskilled extractive industry/construction/transport workers' },
  { code: 194, label: 'Meal preparation assistants' },
  { code: 195, label: 'Street vendors and street service providers' },
];
